#+OPTIONS: toc:nil author:nil email:nil

* Thanks

  To [[https://github.com/trockenasche/fdf2csv][trockenasche]] for starting this project. It seems that the original
  author todo-s have been fully implemented, and perhaps some more.

* General

  FDF is the original [[https://en.wikipedia.org/wiki/PDF#Forms][PDF forms data (only) submission format]]. This script
  converts such files to the popular CSV "spreadsheet" format. It should be
  easy to execute this script on multiple identical format FDF files, to
  build a large single CSV.

* Usage

  ./fdf2csv.py [-dry] [-tab] [-skip] [-empty] filename[#.fdf] [codec]

  Adds row/data to the output filename.csv if it exists. It is assumed
  that the FDF fields are unique; They would become the CSV column
  names.

  A _serno field is introduced if the input filename has a trailing serial
  number.
  
  The input filename can include the file path (with a leading tilde for
  home page). The output CSV has the trailing digits removed.

  ./fdftocsv.sh is a shell script that handles multiple FDF "blobs".

